CreateIndex({
  name: "findUserByEmail",
  unique: false,
  serialized: true,
  source: Collection("users"),
  terms: [{field: ["data", "auth0_email"]}]
});

CreateIndex({
  name: "findPurveyorByDatocmsId",
  unique: false,
  serialized: true,
  source: Collection("purveyorprofiles"),
  terms: [{ field: ["data", "datocms_id"] }]
});

CreateIndex({
  name: "findFavoritePurveyorByUser",
  unique: false,
  serialized: true,
  source: Collection("user_favorite_purveyors"),
  terms: [{ field: ["data", "userId"] }]
});

CreateIndex({
  name: "findRecipeByDatocmsId",
  unique: false,
  serialized: true,
  source: Collection("recipes"),
  terms: [{ field: ["data", "datocms_id"] }]
});

CreateIndex({
  name: "findFavoriteRecipeByUser",
  unique: false,
  serialized: true,
  source: Collection("user_favorite_recipes"),
  terms: [{ field: ["data", "userId"] }]
});

CreateIndex({
  name: "findProductByClSku",
  unique: false,
  serialized: true,
  source: Collection("products"),
  terms: [{ field: ["data", "cl_sku"] }]
});

CreateIndex({
  name: "findFavoriteProductByUser",
  unique: false,
  serialized: true,
  source: Collection("user_favorite_products"),
  terms: [{ field: ["data", "userId"] }]
});
